services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn api.app:app  # note: path and file name
    plan: free
    autoDeploy: true
build:
  pythonVersion: 3.11.4
